[package]
name = "outro_08"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tide = "0.16.0"
serde = { version = "1.0", features = ["derive"] }
ticket_fields = { path = "../../../helpers/ticket_fields" }
anyhow = "1.0.97"
